### ISSUE TITLE
New update is available as of 18th may

### ISSUE THREAD

**Issue by lilduckyjr** [dwisiswant0/ghostify-crack#1]
Stories are marked as viewed due to instagram change, ghostify put out a new update on 18th may which i think resolves this

**Comment by dwisiswant0** [comment]
Trying on new Ghostify update, still didn't view it as anonymous.

**Comment by lilduckyjr** [comment]
> Trying on new Ghostify update, still didn't view it as anonymous.

They've just updated Ghostify extension yesterday and it works

**Comment by lilduckyjr** [comment]
@dwisiswant0 Any update on when new update will be available?

**Comment by Petit376** [comment]
Hi, has the cracked version been updated too? I still cannot view anonymously using the cracked version

**Comment by Petit376** [comment]
> > Trying on new Ghostify update, still didn't view it as anonymous.
> 
> They've just updated Ghostify extension yesterday and it works

Hi, has the cracked version been updated too? I still cannot view anonymously using the cracked version. Pls help.

**Comment by Petit376** [comment]
Hi, any update pls.

**Comment by dwisiswant0** [comment]
Here is the review from their Chrome web store:

![image](https://github.com/dwisiswant0/ghostify-crack/assets/25837540/d8eea99f-65e0-4dea-b75d-aae1b94ddc66)
> https://chrome.google.com/webstore/detail/ghostify-view-instagram-s/ajkkboilpcbfgojiochgfbeblbpcgpga

**Comment by Petit376** [comment]
Ghostify extension seems to work fine now. Can you pls update the cracked version?
